gateway:
  port: 37466
  topics:
    messages: input
    commands:
      request: commands
      response:  commandsReply
  bootstrap: localhost:9092

logging:
  level:
    ROOT: INFO
    com.lukdut.monitoring: DEBUG