spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./test;AUTO_SERVER=TRUE
    platform: h2
    username: test
    password: test
    driverClassName: org.h2.Driver
    schema: classpath:acl-schema.sql
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    com.lukdut.monitoring: DEBUG

server:
  port: 48080

gateway:
  topics:
    messages: input
    commands:
      request: commands
      response:  commandsReply
  bootstrap: localhost:9092
